version: "3"
services:
  superalgos:
    build: 
      context: ..
      dockerfile: ./Docker/Dockerfile
    image: ghcr.io/superalgos/superalgos:latest
    command: ["minMemo"]
    user: "$UID:$GID"
    environment:
      DEMO_MODE: 'true'
      DEMO_MODE_HOST: 'testing-host.testing.network'
    ports:
      - '34248:34248'
      - '18041:18041'
    restart: on-failure
